### ISSUE TITLE
will need e20 builds of osclib

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbnana#4]
would be good to get these available ASAP, so we can update to e20 sometime soon.

**Comment by cjbackhouse** [comment]
Are we doing e20 as part of v09_16_00 or as a later step? I think there are issues with v09_16_00 e19, so I'm wondering if I can skip them and go straight to e20, or if I have to fix things in two steps.

**Comment by wesketchum** [comment]
oh! what issues? was just about to test building.

e20 was going to be for some future release...

**Comment by cjbackhouse** [comment]
osclib v00.09 depends on `root v6_18_04d` whereas larsoft now wants `v6_22_06a`. I think this is an easy fix, but it's kind of a pain because nova and dune have their own ideas of what dependencies they want, and this doesn't map well to a linearly-increasing osclib version number.

**Comment by cjbackhouse** [comment]
`osclib v00.10` now contains an e20 version.

Only `stanfree` versions exist for e19/e20/c7, since 1) there is no e20 stan_math yet and 2) apparently stan moved all their headers around in the most recent version. This has no impact on SBN right now, but other experiments, and future-SBN, will not be able to use this version since they require stan for flashy Bayesian analysis.

**Comment by wesketchum** [comment]
Closing as we are making e20 releases now.
