### ISSUE TITLE
Potential Issue in (Livetime) Exposure Accounting with CAFAna

### ISSUE THREAD

**Issue by brucehoward-physics** [SBNSoftware/sbnana#52]
I believe there is an issue in the Livetime accounting in the CAFs. Tagging @jedori0228 as watcher since Jack pointed out a message from Jaesung that got me thinking about this (I would also tag Jack, but don't see him in the users).

There are a few possible philosophies for generating neutrino beam MC samples that I can think of. The most straight-forward to understand way seems to be if you literally simulated spills whether there were nu interactions near the detector or not. However, what I understand that we do is pick some volume and simulate a given number of neutrino spills with interactions in this volume (which by the way, we sometimes filter to get just events with neutrinos in the active volume when the total gen volume is a bit larger: at least in ICARUS).

I think/guess — I’m not an expert here but I think — that the POT assigned to a given event must be proportional to the volume size (and I would guess possibly materials??) since a neutrino interaction IN our considered volume may take (on average) more than 1 spill’s worth of POT.

For example if you expect 1 neutrino in the simulated volume over 5 spills, then the POT required for a given event would then be something like 5 times the nominal POTPerSpill (on average), no? Or, putting it another way, getting an event in half a detector “requires more POT” than getting an event in a full detector.

As a partial check of this, I did a test run of 50 events in ICARUS with the volDetEnclosure volume and volCryostat volumes, where I think the DetEnclosure volume is larger. Asking the GENIE Helper to print out some stuff (I slightly moved and uncommented a printout that was in the [Stop() function](https://nusoft.fnal.gov/larsoft/doxsvn/html/classevgb_1_1GENIEHelper.html#affc91e28bcc51a15b3e3c63c0da96f83) ), I got some details. The POTPerSpill printed out 6E13, the expected setting. However, the SpillExposure over these 50 events was on average significantly higher than this using the DetEnclosure option, and it was even higher when using the Cryostat option.

I’m not an expert, but this is my observation, and it fits with what @jedori0228 was seeing (more POT/Event reported by a CAF file than the nominal POTPerSpill).

Now, this points us to where I believe there is at least one exposure accounting bug. The Livetime is tied to fNGenEvt. However if what I describe above is correct, then the POT/Event will actually be different than the POT/Spill, and it will be the number of beam spills that we want to know about for scaling the cosmics no? Maybe one can scale Livetime by the ratio of (POT/Event) / (nominal POTPerSpill) to recover this in the meantime?

Side/follow-up question — does running with extra area and then filtering run us into further problems? What if it changes the average nuclear density (cross-section) or something? Here I fully defer to experts…

I don't know who are the right experts to tag here, but I tag @cjbackhouse since I understand he set the `Livetime` to be NGenEvt, and I tag @PetrilloAtWork as he has been involved in some fashion with the gen scripts and committed the file using volDetEnclosure. Please tag others as needed if you know better people to tag!

[[ I’m putting this Issue in `sbnana` but if this is better placed in `sbncode` or elsewhere let me know! ]]

**Comment by PetrilloAtWork** [comment]
What is the definition of `Livetime`? `nGenEvt` sounds like a number of events, not a time.

> does running with extra area and then filtering run us into further problems? What if it changes the average nuclear density (cross-section) or something?

When you generate a sample, GENIE tells you how many POT that full sample reflects. That number of POT is what you will carry through the whole analysis, independently from the following selection. POT are a beam property, and nothing in the detector should affect them.

**Comment by brucehoward-physics** [comment]
I think the `time` part of the word is just because it's a carry-over from NOvA where it did actually use time. In SBN it has been meaning "spill" and is so we have something of meaning with which to scale the cosmic expectation. But I claim it doesn't _really mean_ spill in its current implementation, hence why I'm filing the issue.

Thanks for the second paragraph -- I think I was most worried about if the volume contained more or less of the surroundings then that might impact the neutrinos per POT (for example by changing the average nuclear density). But while the number of neutrinos per POT will change, I guess you should still get the same neutrinos in the active volume per POT, so that's fine.

**Comment by cjbackhouse** [comment]
Agree with all the description of the philosophy behind POT accounting when you expect less than one event per spill in the detector.

About the livetime: yes, the word is a historical accident, and means "spills" in an SBN context. You can think of it as implying an effective livetime of nspills * timing window if you want. We could consider changing it, but I'm not sure to what (it still needs to be able to mean a number of seconds for nova). "Exposure" is correct, but I think overlaps in meaning with regular POT. For now I think it's a wart we can deal with.

`sbnana/SBNAna/anademo/demo_exposure.C` is my source for how we are supposed to do this. It is also the logic the oscillation fit [will] use.

The out-of-time component of the cosmic background (i.e. from files with overlaid neutrinos and cosmics) relies on the existence of a neutrino interaction for its meaning, so comes along "for free" with the POT scaling of the neutrinos. In other words, the ratio of neutrino events to this type of background is fixed, and the files should already have the appropriate scaling in them.

The in-time component of the cosmic background (i.e. from files simulated with no neutrinos in them) has to scale with how many spills there would have been in reality, not just the number we simulated for practical reasons. That's why we compute it as (total POT)/(expected beam intensity). This is what `demo_exposure.C` refers to as `nominalLivetime`. The other reason is that this number depends on an assumption for the beam intensity, which is something the FD MC can be simulated basically independently of. In a fit to real data we would scale this to just the count of spills when the detector was live for data.

At no point so far does the number of spills actually simulated in the beam simulation come into things. That is, NGenEvt/Livetime() in the beam MC was not used for anything yet. We based things on the beam MC and the in-time/cosmics-only livetime.

There is then an additional wrinkle about not double-counting the "in-time" events that actually correspond to time that was already simulated in the out-of-time files, which does bring those numbers in. But I think the issue was talking about more general considerations, which I hope I covered above.

This took me weeks to get my head around the first time. And about ten minutes to correctly re-remember here. It should definitely be written down somewhere more official than a demo macro, and potentially gone over by experts, but I'm not sure where or by who is best.

**Comment by brucehoward-physics** [comment]
Okay so just don't think about `Livetime` of the beam MC sample unless we specifically want to know how many spills will have had a useful interaction in it. Got it -- sorry for the false alarm.

**Comment by wesketchum** [comment]
@brucehoward-physics should we close this then?

**Comment by brucehoward-physics** [comment]
Yes I think so!

**Comment by PetrilloAtWork** [comment]
As a side comment, I suggest we take care not to use "spill" and "event" interchangeably.
"Event" is a heavily overloaded word, but I tend to interpret it like a record of something that happened in a single detector readout (like an `art::Event`). Since in neutrino simulated samples we do not record spills with no neutrino interaction, the two concepts do not match (as far as I know, they do match in background simulation).
